<?xml version="1.0"?>
<robot name="raspimouse_on_gazebo"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="lidar" default="none" />

  <xacro:include filename="$(find raspimouse_description)/urdf/common.xacro" />
  <xacro:include filename="$(find raspimouse_description)/urdf/body/body.urdf.xacro" />
  <xacro:include filename="$(find raspimouse_description)/urdf/wheel/wheel.urdf.xacro" />
  <xacro:include filename="$(find raspimouse_description)/urdf/sensors/lightsens.urdf.xacro" />
  <xacro:include filename="$(find raspimouse_description)/urdf/sensors/lrf.urdf.xacro" />

  <!-- =============== Link & Joint =============== -->
  <!-- Base -->
  <link name="base_footprint" />

  <xacro:base parent="base_footprint" lidar="$(arg lidar)">
    <origin xyz="0 0 0.00185" />
  </xacro:base>

  <!-- Wheel -->
  <xacro:wheel prefix="right" parent="base_link">
    <origin xyz="0 -0.0425 0.02215" rpy="1.57 0 0" />
    <axis xyz="0 0 -1" />
  </xacro:wheel>
  <xacro:wheel prefix="left" parent="base_link">
    <origin xyz="0 0.0425 0.02215" rpy="-1.57 0 0" />
    <axis xyz="0 0 1" />
  </xacro:wheel>

  <!-- Sensors -->
  <xacro:light_sensor prefix="rf" parent="base_link">
    <origin xyz="0.04 -0.045 0.032" rpy="0 0 0" />
  </xacro:light_sensor>

  <xacro:light_sensor prefix="rs" parent="base_link">
    <origin xyz="0.059 -0.01 0.032" rpy="0 0 -1.04" />
  </xacro:light_sensor>

  <xacro:light_sensor prefix="ls" parent="base_link">
    <origin xyz="0.059 0.01 0.032" rpy="0 0 1.04" />
  </xacro:light_sensor>

  <xacro:light_sensor prefix="lf" parent="base_link">
    <origin xyz="0.04 0.045 0.032" rpy="0 0 0" />
  </xacro:light_sensor>

  <xacro:if value="${'$(arg lidar)' == 'urg'}">
    <xacro:lrf_sensor prefix="urg_lrf_link" parent="base_link">
      <origin xyz="0.0 0.0 0.14060" rpy="0 0 0" />
    </xacro:lrf_sensor>
  </xacro:if>


  <!-- =============== Gazebo =============== -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so" />
  </gazebo>
  
  <!-- Sensors -->
  <xacro:lightsensor_gazebo prefix="rf" base_rad="0" rad_range="0.3" min_range="0.01" max_range="0.6" robot_namespace="raspimouse_on_gazebo" />
  <xacro:lightsensor_gazebo prefix="rs" base_rad="-1.04" rad_range="0.3" min_range="0.01" max_range="0.6" robot_namespace="raspimouse_on_gazebo" />
  <xacro:lightsensor_gazebo prefix="ls" base_rad="1.04" rad_range="0.3" min_range="0.01" max_range="0.6" robot_namespace="raspimouse_on_gazebo" />
  <xacro:lightsensor_gazebo prefix="lf" base_rad="0" rad_range="0.3" min_range="0.01" max_range="0.6" robot_namespace="raspimouse_on_gazebo" />

  <xacro:if value="${'$(arg lidar)' == 'urg'}">
    <xacro:lrf_gazebo prefix="urg" base_rad="0" rad_range="4.71" min_range="0.10" max_range="5.6" />
  </xacro:if>

  <!-- DiffDriveController -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <robotNamespace>raspimouse_on_gazebo</robotNamespace>
      <updateRate>50</updateRate>
      <legacyMode>false</legacyMode>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2.0}</wheelDiameter>
      <publishWheelJointState>true</publishWheelJointState>
      <rosDebugLevel>na</rosDebugLevel>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishOdomTF>false</publishOdomTF>
      <wheelAcceleration>0</wheelAcceleration>
      <wheelTorque>5</wheelTorque>
      <odometrySource>world</odometrySource>
      <publishTf>1</publishTf>
    </plugin>
  </gazebo>

  <raspimouse_on_gazebo/>
</robot>
